import fs from 'node:fs';
import path from 'node:path';

const engineJsDest = path.resolve('public/js/scoring-engine.js');

const header = `// Auto-generated browser bundle from src/engine/ScoringEngine.ts
// DO NOT EDIT THIS FILE DIRECTLY! Edit src/engine/ScoringEngine.ts instead.
`;

// Read the pure browser engine source code
const browserEngineContent = fs.readFileSync(engineJsDest, 'utf8');

// Prepend header warning
if (!browserEngineContent.startsWith('// Auto-generated')) {
  fs.writeFileSync(engineJsDest, header + browserEngineContent, 'utf8');
}

console.log('✅ Successfully validated public/js/scoring-engine.js bundle build!');
