import fs from 'node:fs';
import path from 'node:path';

const compiledSrc = path.resolve('dist/src/engine/ScoringEngine.js');
const engineJsDest = path.resolve('public/js/scoring-engine.js');

if (!fs.existsSync(compiledSrc)) {
  console.error('Error: dist/src/engine/ScoringEngine.js does not exist. Run tsc first.');
  process.exit(1);
}

let content = fs.readFileSync(compiledSrc, 'utf8');

// Replace module import statement with inline isPhysicalBall helper
content = content.replace(
  "import { isPhysicalBall } from '../models/types.js';",
  `function isPhysicalBall(ball) {
    if (!ball || ball.isAdjustment) return false;
    return ball.isLegalBall !== false && ball.extrasType !== 'WIDE' && ball.extrasType !== 'NO_BALL';
  }`
);

// Strip export keyword for non-module browser scripts
content = content.replace("export class ScoringEngine", "class ScoringEngine");

// Expose on window
content += `\nif (typeof window !== 'undefined') { window.ScoringEngine = ScoringEngine; }\n`;

const header = `// Auto-generated browser bundle from src/engine/ScoringEngine.ts
// DO NOT EDIT THIS FILE DIRECTLY! Edit src/engine/ScoringEngine.ts instead.
`;

fs.writeFileSync(engineJsDest, header + content, 'utf8');
console.log('✅ Successfully bundled dist/src/engine/ScoringEngine.js -> public/js/scoring-engine.js');
